version: "3.9"
services:
  games-server:
    image: "demo-server"
    container_name: "pollos-demo-server"
    ports:
      - "8000:8000"
  postgresql:
    image: "postgres"
    container_name: "pollos-demo-postgresql"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=myusername
      - POSTGRES_PASSWORD=mypassword
    volumes:
      - /data\:/var/lib/postgresql/data
  games-client:
    image: "demo-client"
    container_name: "pollos-demo-client"
    ports:
      - "3000:443"
  # TODO: move out env args

  nginx:
    image: nginx:latest
    volumes:
      - ../nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - games-client
    ports:
      - "443:4000"
