"""New Migration 2

Revision ID: c4be45be3e31
Revises: be9745054839
Create Date: 2022-06-12 04:04:06.056228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4be45be3e31'
down_revision = 'be9745054839'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
