"""New Migration 3

Revision ID: cee2f0a6607c
Revises: c4be45be3e31
Create Date: 2022-06-12 04:13:56.050918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "cee2f0a6607c"
down_revision = "c4be45be3e31"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "association",
        sa.Column("post_id", sa.Integer(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["post_id"],
            ["post.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("association")
    # ### end Alembic commands ###
